--TASK 6 BUSINESS QUESTIONS
SELECT * FROM customers;
SELECT * FROM subscriptions;

--QUES 1:Customer's full name, state, subscription plan, payment method, and monthly revenue
SELECT concat(c.first_name, ' ' , last_name) AS Fullname,
                  c.state,
                 s.plan_type, payment_method, 
                 SUM(s.revenue) AS monthly_revenue
FROM customers c
INNER JOIN subscriptions s
on c.Customer_ID = s.Customer_ID
GROUP BY concat(c.first_name, ' ' , last_name), state, 
s.plan_type, payment_method
ORDER BY fullname;

--QUES 2:Calculate the total revenue generated from each subscription plan.
SELECT Plan_type, sum(revenue) AS Total_revenue
FROM subscriptions
GROUP BY plan_type;

--QUES 3: Determine the average monthly revenue generated by customers in each region.
SELECT c.region, round(avg(s.revenue),2) AS Average_monthly_revenue
FROM customers c
INNER JOIN subscriptions s
ON c.Customer_ID = s.Customer_ID
GROUP BY region;

--QUES 4: How many customers are enrolled in each subscription plan?
SELECT Plan_type, count(*)
FROM customers
GROUP BY plan_type;

--QUES 5: Which states generate the highest total revenue?Display the total revenue for every state in descending order.
SELECT c.state, sum(S.revenue) AS Total_revenue
FROM customers c
INNER JOIN subscriptions s
ON c.Customer_ID = s.Customer_ID
GROUP BY state
ORDER BY Total_revenue DESC;

--QUESS 6: Calculate the average customer age for each subscription plan
SELECT s.plan_type, round(avg(c.age)) AS average_age
FROM customers c
INNER JOIN subscriptions s
ON c.Customer_ID =s.Customer_ID
GROUP BY s.plan_type;

--QUES 7: Determine the total revenue collected through each payment method
SELECT payment_method, sum(revenue) AS Total_revenue
FROM subscriptions
GROUP BY payment_method;

--QUES 8: Identify the highest revenue generated under each subscription plan.
SELECT Plan_type, MAX(revenue) AS Maximum_revenue
FROM subscriptions
GROUP BY Plan_type;

--QUES 9: Identify the lowest revenue generated under each subscription plan
SELECT Plan_type, MIN(revenue) AS Minimum_revenue
FROM subscriptions
GROUP BY Plan_type;

--QUES 10: How many Active customers are there in each region?
SELECT region, COUNT(*) AS Active_Customers
FROM customers
WHERE Status = 'Active'
GROUP BY region;

--QUES 11: Create an Age_Group column using SQL (Under 30, 30-50, Above 50). Display the customer's full name together with the age group.
SELECT concat(first_name,' ',last_name) AS Fullname,
     CASE
	 WHEN age <  30 THEN 'Young'
	 WHEN age BETWEEN 30 AND 50 THEN 'Adult'
	 ELSE 'Elder'
	 END  AS age_group
FROM customers;

--QUES 12: Display the number of customers in each Age_Group.
SELECT
     CASE
	 WHEN age <  30 THEN 'Young'
	 WHEN age BETWEEN 30 AND 50 THEN 'Adult'
	 ELSE 'Elder'
	 END  AS age_group,
	 COUNT(*)
FROM customers
GROUP BY age_group;

--QUES 13: Display the customer names entirely in uppercase together with their subscription plans
SELECT UPPER(first_name) AS first_name, 
UPPER(last_name) AS last_name, 
UPPER(Plan_type) AS subscription_plan
FROM customers;

--QUES 14: Display the year each customer joined together with their subscription plan.
SELECT concat(first_name,' ',last_name) AS Customer,
        EXTRACT(Year from join_date) join_Year,
		plan_type AS subscription_plan
FROM customers
ORDER BY join_Year;

--QUES 15: : Identify the Top 10 highest-paying customers, State, Subscription Plan, and Monthly Revenue, sorted from highest to lowest.
SELECT concat(c.first_name,' ',c.last_name) AS Customer,
       c.state, s.Plan_type,s.revenue 
FROM customers c
INNER JOIN subscriptions s
ON c.Customer_ID = s.Customer_ID
ORDER BY s.revenue DESC
LIMIT 10;

--QUES 16: Calculate the average monthly revenue generated by customers in each state
SELECT c.state, round(AVG(s.revenue),2) AS Average_monthly_revenue
FROM customers c
INNER JOIN subscriptions s
ON c.Customer_ID = s.Customer_ID
GROUP BY state;

--QUES 17: Determine the total number of customers grouped by:Region, Subscription Plan
SELECT region, plan_type,
COUNT(*) AS customer_count
FROM customers
GROUP BY region, plan_type
ORDER BY region;

--QUES 18: Display all customers whose revenue is above the overall average revenue.
SELECT concat(c.first_name,' ',c.last_name) AS customer_name,
       s.plan_type,
	   s.revenue
FROM customers c
INNER JOIN subscriptions s
ON c.Customer_ID = s.Customer_ID
WHERE s.revenue>(SELECT AVG(revenue)
FROM subscriptions);

--QUES 19: Create a Revenue Category column (Low, Medium, High) using CASE WHEN. Display Customer Name, Revenue, and Revenue Category.
SELECT concat(c.first_name,' ',c.last_name) AS Customer_name,
        s.revenue,
       CASE
	   WHEN s.revenue BETWEEN  3000 AND 5000 THEN 'Low'
	   WHEN s.revenue BETWEEN  5000 AND 7000 THEN 'Medium'
	   ELSE  'High'
	   END AS revenue_categories
FROM customers c
INNER JOIN subscriptions s
ON c.Customer_ID  = s.Customer_ID
ORDER BY s.revenue desc;

--QUES 20: Produce a management report showing Region, Total Customers, Average Age, Total Revenue, Highest Revenue, and Lowest Revenue.
SELECT c.region, COUNT(*) AS Total_Customers,
        round(AVG(c.age)) AS average_age,
		sum(s.revenue) AS Total_revenue,
		MAX(s.revenue) AS Highest_revenue,
		MIN(s.revenue) AS Lowest_revenue
FROM customers c
INNER JOIN subscriptions s
ON c.Customer_ID = s.Customer_ID
GROUP BY region;