--BUSINESS QUESTION

SELECT * FROM customers;

--Question 1:Customer Count
SELECT COUNT(Customer_ID) AS "Total Customers"
FROM customers;

SELECT * FROM subscriptions;

--Question 2:Total Customer per Plan type
SELECT Plan_type, count(Customer_ID) AS "Total Customers"
FROM subscriptions
Group by Plan_type;

--Question 3: Average Age by Region
SELECT Region, AVG(Age) AS "Average Age"
FROM customers
Group by Region;


--Question 4: Revenue generated by Plan-type per Month
SELECT
    TO_CHAR(subscription_date, 'Month YYYY') AS "Month",
    plan_type,
    SUM(revenue) AS "Total_Monthly_Revenue"
FROM subscriptions
GROUP BY TO_CHAR(subscription_date, 'Month YYYY'), plan_type
ORDER BY month, plan_type;


--Question 5: Average Age by State
SELECT State, AVG(Age) AS "Average Age"
from customers
Group by state, Age;


--Question 6: Active Customers by Region
SELECT Region, count(Customer_ID) AS "Active Customers"
FROM customers
WHERE Status = 'Active' 
Group by Region;


--Question 7: Revenue by Payment-method
SELECT Payment_Method, sum(Revenue) AS "Total Revenue"
FROM subscriptions
Group by Payment_Method;


--Question 8: Highest Revenue generated by Plan-type per Month
SELECT Plan_type, 
           TO_CHAR(Subscription_Date,'Month YYYY') AS "Month",
           MAX(Revenue) AS "Max_Monthly_Revenue"
    FROM subscriptions
    GROUP BY Plan_type, TO_CHAR(Subscription_Date, 'Month YYYY')
;


--Question 9: Lowest Revenue generated by Plan-type per Month
SELECT Plan_type, 
           TO_CHAR(Subscription_Date,'Month YYYY') AS "Month",
           MIN(Revenue) AS "Min_Monthly_Revenue"
    FROM subscriptions
    GROUP BY Plan_type, TO_CHAR(Subscription_Date, 'Month YYYY')
;


--Question 10: Average Data usage by Plan-type per Month
SELECT Plan_type, 
           TO_CHAR(Subscription_Date,'Month YYYY') AS "Month",
           AVG(Data_GB) AS "Average Monthly GB"
FROM subscriptions
Group by Plan_type, TO_CHAR(Subscription_Date,'Month YYYY');
